auto: true
safe: false
source: ./
destination: ./_build
lsi: false
permalink: /blog/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

title: Collective Cognition
tagline:
author:
  name: William Blanchette
  email: wb@collectivecognition.com
  github: collectivecognition
  twitter: wblanchette
  feedburner: 

url: http://collectivecognition.com

mini_magick:
    thumbnail:
        source: images/blog
        destination: images/blog/thumbnails
        resize: "630x400"