audo: true
safe: true
source: ./
destination: ./_build
lsi: false
permalink: /:categories/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

title : Jekyll Bootstrap
tagline: Site Tagline
author :
  name : Name Lastname
  email : blah@email.test
  github : username
  twitter : username
  feedburner : feedname

production_url : http://collectivecognition.github.io/collectivecognition.com