safe: false
source: ./
lsi: false
permalink: /blog/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", edit, publish, build]
pygments: true
markdown: kramdown

title: Collective Cognition
tagline:
author:
  name: William Blanchette
  email: wb@collectivecognition.com
  github: collectivecognition
  twitter: wblanchette
  feedburner: 

url: http://collectivecognition.com

sass:
  style: expanded
  deploy_style: compressed
  compile_in_place: false

mini_magick:
    thumbnail:
        source: images/blog/original
        destination: images/blog/thumbnails
        resize: "920x"
    games:
        source: images/games/original
        destination: images/games/thumbnails
        resize: "293x"
    web:
        source: images/web/original
        destination: images/web/thumbnails
        resize: "470x"