auto: true
safe: true
source: ./
destination: ./_build
lsi: false
permalink: /:categories/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

title: Collective Cognition
tagline:
author:
  name: William Blanchette
  email: wb@collectivecognition.com
  github: collectivecognition
  twitter: wblanchette
  feedburner: 

production_url : http://collectivecognition.github.io/collectivecognition.com