auto: true
safe: false
source: ./
lsi: false
permalink: /blog/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", edit, publish, build]
pygments: true

title: Collective Cognition
tagline:
author:
  name: William Blanchette
  email: wb@collectivecognition.com
  github: collectivecognition
  twitter: wblanchette
  feedburner: 

url: http://localhost:4000

mini_magick:
    thumbnail:
        source: images/blog/original
        destination: images/blog/thumbnails
        resize: "630x400"
    games:
        source: images/games/original
        destination: images/games/thumbnails
        resize: "200x122"
    web:
        source: images/web/original
        destination: images/web/thumbnails
        resize: "x140"